# Generated by Django 4.1.3 on 2023-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, verbose_name='uid')),
                ('createdTime', models.BigIntegerField(verbose_name='time created')),
                ('username', models.CharField(max_length=64, verbose_name='email')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
            ],
        ),
    ]
