# Generated by Django 4.1.3 on 2023-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionUID', models.CharField(max_length=64, verbose_name='session uid')),
                ('userUID', models.CharField(max_length=64, verbose_name='user uid')),
                ('createdTime', models.BigIntegerField(verbose_name='time created')),
            ],
        ),
    ]
