# Generated by Django 4.1.3 on 2023-05-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_username_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUID', models.CharField(max_length=64, verbose_name='uid')),
                ('sex', models.CharField(max_length=1)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('exercises', models.JSONField(default=dict)),
            ],
        ),
    ]
