# Generated by Django 4.1.3 on 2023-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUID', models.CharField(max_length=64, verbose_name='uid')),
                ('createdTime', models.BigIntegerField(verbose_name='time created')),
                ('startTime', models.BigIntegerField(blank=True, null=True, verbose_name='time started')),
                ('endTime', models.BigIntegerField(blank=True, null=True, verbose_name='time ended')),
                ('type', models.CharField(max_length=256, verbose_name='record type')),
                ('value', models.FloatField(verbose_name='record value')),
            ],
        ),
    ]
