# Generated by Django 4.1.3 on 2023-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_healthevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUID', models.CharField(max_length=64, verbose_name='uid')),
                ('createdTime', models.BigIntegerField(verbose_name='time created')),
                ('type', models.CharField(max_length=256, verbose_name='plan type')),
                ('plan_data', models.JSONField(default=dict)),
            ],
        ),
    ]
