# Generated by Django 4.1.3 on 2023-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_planevent_plan_data_planevent_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='weight',
            field=models.FloatField(),
        ),
    ]
