# Generated by Django 4.1.3 on 2023-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersettings_height_alter_usersettings_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevent',
            name='progressRatio',
            field=models.FloatField(default=0, verbose_name='progress ratio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='height',
            field=models.FloatField(verbose_name='height in cm'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='weight',
            field=models.FloatField(verbose_name='weight in kg'),
        ),
    ]
