# Generated by Django 4.2 on 2023-06-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_planevent_progressratio_alter_usersettings_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='height',
            field=models.FloatField(default=0.01, verbose_name='height in cm'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='weight',
            field=models.FloatField(default=0.01, verbose_name='weight in kg'),
        ),
    ]
