# Generated by Django 4.2 on 2023-06-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usersettings_height_alter_usersettings_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevent',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='plan name'),
            preserve_default=False,
        ),
    ]
